services:
  db:
    image: postgres:14
    container_name: app-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_PORT: ${HTTP_PORT}
      DATABASE_DSN: ${DATABASE_DSN}
    volumes:
      - ./migrations:/migrations:ro
    ports:
      - "${HTTP_PORT:-8080}:8080"

volumes:
  db_data:
